apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels: # says all pods with this label belong to this deployment
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: # shows where the pods that belong to this service are.
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # exposes this port to the world
      targetPort: 27017 # points to the port of the deployment